# Generated by Django 4.2.29 on 2026-03-08 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='image',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='monthly_listeners',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='description',
        ),
        migrations.RemoveField(
            model_name='newslettersubscriber',
            name='active',
        ),
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='song',
            name='language',
        ),
        migrations.RemoveField(
            model_name='song',
            name='meaning',
        ),
        migrations.RemoveField(
            model_name='song',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='song',
            name='producers',
        ),
        migrations.RemoveField(
            model_name='song',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='song',
            name='trivia',
        ),
        migrations.RemoveField(
            model_name='song',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='song',
            name='writers',
        ),
        migrations.RemoveField(
            model_name='usersubmission',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='usersubmission',
            name='song',
        ),
        migrations.AddField(
            model_name='song',
            name='cover_url',
            field=models.URLField(blank=True, help_text='Album/song cover image URL'),
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lyrics.genre'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image_url',
            field=models.URLField(blank=True, help_text='Paste an image URL'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='icon',
            field=models.CharField(default='🎵', max_length=10),
        ),
        migrations.AlterField(
            model_name='song',
            name='youtube_id',
            field=models.CharField(blank=True, help_text='YouTube video ID — the part after ?v= e.g. dQw4w9WgXcQ', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
