# Generated by Django 4.2.29 on 2026-03-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0002_remove_artist_created_at_remove_artist_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='show_in_footer',
            field=models.BooleanField(default=False, help_text='Show this genre in the footer'),
        ),
    ]
