# Generated by Django 4.2.29 on 2026-03-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0003_genre_show_in_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='composer',
            field=models.CharField(blank=True, help_text="Composer name(s), e.g. 'Phuahtu'", max_length=300),
        ),
    ]
